### ISSUE TITLE
How to get started

### ISSUE THREAD

**Issue by zahmed80** [BriefFiniteElementNet/BFE.Net#10]
I am trying to figure out.. how to get started. there is no .DLL file or anything. how to reference.. what to reference to. 
Kindly help in newbie how to start

**Comment by epsi1on** [comment]
Hi,
in page
https://bfenet.readthedocs.io/en/latest/index.html
from left panel navigate to "Getting Started" section and read it's parts.

thanks

**Comment by ceanwang** [comment]
Great, I got this one working.

Want to try a win form program now.

**Comment by ceanwang** [comment]
After the first success I used the generated DLLs for a VB project. Also need to imports CSparse like these:

`Imports BriefFiniteElementNet
Imports BriefFiniteElementNet.Elements

Imports CSparse
Imports CSparse.Double
Imports CSparse.Double.Factorization
Imports CSparse.Storage`
 
Now trying to compile the BriefFiniteElementNet.CodeProjectExamples project. It seems need to compile BriefFiniteElement.Controls first. After got a new controls DLL,, the Examples compiled, but exit with an error when execute.  Will figure it out.

**Comment by epsi1on** [comment]
> but exit with an error when execute. Will figure it out.

can you please give more information about the error? (screenshot etc.)

**Comment by ceanwang** [comment]
Because the Main only do  DocSnippets.Test1();
and Test1() doesn't print anything, so it should be a normal run. No problem.

**Comment by epsi1on** [comment]
Hello Mohammad Sadegh,
Can you please give more information on what is the problem / error you see when building the project?
Also my personal email is ehsan[dot]ma[atSign]gmx[dot]com, please e-mail me.
Thanks
