### ISSUE TITLE
Help on "Matrix must be symmetric positive definite" error

### ISSUE THREAD

**Issue by ceanwang** [BriefFiniteElementNet/BFE.Net#11]
Hi,

Tried to calculate a 2d truss with code below, but got a message saying "Matrix must be symmetric positive definite". What's wrong with the code?

Thanks for help.

Cean

        private static void Truss2D()
        {
            Console.WriteLine("Simple 2D truss with 3 members");
            
            var model = new Model();

            var n1 = new Node(0, 0, 0);
            n1.Label = "n1";//Set a unique label for node
            var n2 = new Node(1, 0, 1.732) { Label = "n2" };//using object initializer for assigning Label
            var n3 = new Node(1, 0, 0) { Label = "n3" };

            var e1 = new TrussElement2Node(n1, n2) { Label = "e1" };
            var e2 = new TrussElement2Node(n2, n3) { Label = "e2" };
            var e3 = new TrussElement2Node(n1, n3) { Label = "e3" };

            e1.A = e2.A = e3.A  = 0.001;
            e1.E = e2.E = e3.E  = 200e9;

            model.Nodes.Add(n1, n2, n3);
            model.Elements.Add(e1, e2, e3);

            n1.Constraints  = Constraints.Fixed;
            n2.Constraints = Constraints.RotationFixed;
            n3.Constraints = Constraints.RotationFixed;
            
            var force = new Force(10000, 0, 0, 0, 0, 0);
            n2.Loads.Add(new NodalLoad(force));//adds a load with LoadCase of DefaultLoadCase to node loads

            model.Solve();

            Console.ReadKey();

        }

**Comment by epsi1on** [comment]
Hi,
**Reason:** The error ``Matrix must be symmetric positive definite``, is saying that application is calculated the stiffness matrix of structure and when it tries to solve the eq system, it turns out that stiffness matrix is not [Symmetric](https://en.wikipedia.org/wiki/Symmetric_matrix) [Positive Definite](https://en.wikipedia.org/wiki/Positive-definite_matrix) matrix, but it always should be. The reason is that your model is not stable because of elements you used.
**Solution**: Use FrameElement2Node or BarElement instead of TrussElement2Node and see what happens

**Comment by ceanwang** [comment]
Yes, BarElement worked.  

Is FrameElement2Node the replacement of  BarElement?

**Comment by epsi1on** [comment]
the BarElement is new version of FrameElement and TrussElement. By setting the ``BarElement.Behavior`` you can set the Frame or Truss behavior to bar element ([more info](https://bfenet.readthedocs.io/en/latest/elements/finiteElements/Bar/behavs.html))

**Comment by epsi1on** [comment]
Also please note that the truss you made in first post is not geometrically stable. You should ensure the stability of model before solving the model, otherwise you always get the positive definite error on solving the model.

**Comment by ceanwang** [comment]
For unstable, do you mean the Constraints? For n3, I need to add dz and dy Fixed. and fix dy for n2.

**Comment by epsi1on** [comment]
yes, I mean constraints. For a truss model all rotational DoFs should be fixed. also if you model 2d, you should also fix translation DoF in Y. For support nodes all DoF should be fixed. it means for your example:
```
n1.Constraints  = Constraints.RotationFixed & Constraints.FixedDY;
        n2.Constraints = Constraints.RotationFixed;
        n3.Constraints = Constraints.RotationFixed;
```

Try this code:

```
            Console.WriteLine("Simple 2D truss with 3 members");

            var model = new Model();

            var n1 = new Node(0, 0, 0);
            n1.Label = "n1";//Set a unique label for node
            var n2 = new Node(1, 0, 1.732) { Label = "n2" };//using object initializer for assigning Label
            var n3 = new Node(1, 0, 0) { Label = "n3" };

            var e1 = new TrussElement2Node(n1, n2) { Label = "e1" };
            var e2 = new TrussElement2Node(n2, n3) { Label = "e2" };
            var e3 = new TrussElement2Node(n1, n3) { Label = "e3" };

            e1.A = e2.A = e3.A = 0.001;
            e1.E = e2.E = e3.E = 200e9;

            model.Nodes.Add(n1, n2, n3);
            model.Elements.Add(e1, e2, e3);

            n1.Constraints = Constraints.Fixed;
            n2.Constraints = Constraints.RotationFixed & Constraints.FixedDY; 
            n3.Constraints = Constraints.Fixed;

            var force = new Force(10000, 0, 0, 0, 0, 0);
            n2.Loads.Add(new NodalLoad(force));//adds a load with LoadCase of DefaultLoadCase to node loads

            model.Solve();

            var d = n2.GetNodalDisplacement();

            Console.WriteLine("displacement on node 2: " + d.DX.ToString());

            Console.ReadKey();
```

**Comment by ceanwang** [comment]
All good now. Thx.
