### ISSUE TITLE
Partial Releases of Frame Elements

### ISSUE THREAD

**Issue by aurimasmb** [BriefFiniteElementNet/BFE.Net#4]
Hi @epsi1on,

Thanks for this great library!
I'm trying to model a structure where beam elements are fixed at one end, and pinned at their other end. In some situations I will have beam elements meeting at a connection where some of the beam elements are fixed with respect to that node, and others are pinned (for example, a continuous chord of a truss with pin-jointed web members connected to it).

Is this possible with the current implementation of BFE.net and if so, which is the recommended approach?

I have seen the `FrameElement2Node.HingedAtStart` and `.HingedAtEnd` properties but I'm not sure exactly how to interpret these. 

Thanks!
Auri

**Comment by epsi1on** [comment]
hi,
 `FrameElement2Node.HingedAtStart` and `.HingedAtEnd` properties defines if connection of FrameElement2Node to `FrameElement2Node.StartNode` or `FrameElement2Node.EndNode` are hinged (partial) or full rigid connection. Currently there is no other option for partial end connections.

**Comment by epsi1on** [comment]
Also you can find more information on this file:
https://www.mathworks.com/matlabcentral/fileexchange/27012-matrix-structural-analysis
as formulation used in FrameElement2Node is C# port of this MATLAB file.

Thanks
