### ISSUE TITLE
Deformation loads applied on beam elements

### ISSUE THREAD

**Issue by Ludivan** [BriefFiniteElementNet/BFE.Net#5]
Hello,

First thank you for this amazing library !

I would like to model concrete shrinkage for composite sections, to do so I would like to apply deformation load cases on the beams. For gradient temperature loads the approach would be the same.

At this stage would it be possible ?

Thanks
Best regards
Luc

**Comment by epsi1on** [comment]
Hi Luc,
Unfortunately neither deformation loadcase and temperature gradient are implemented in the library yet. 
By the way the part of code for finding deformed shape of beam under given loads is in progress now.

Thanks

**Comment by Ludivan** [comment]
Hi epsi1on,
Thank you for your answer and the update.
Talk to you soon
BR
Luc

**Comment by ceanwang** [comment]
I'd like to try beam elements. Is there a simple example?Thx.

**Comment by epsi1on** [comment]
@ceanwang please do create new issue for your question, do not use unappropriated issues for your requests. thanks

yes, take a look at [here](https://bfenet.readthedocs.io/en/latest/example/loadcasecomb/index.html)
