### ISSUE TITLE
3 Noded Plate bending and Membrane element

### ISSUE THREAD

**Issue by Murtasgh** [BriefFiniteElementNet/BFE.Net#7]
Hi,

I've been using this library for some time now, but mostly in structures comprised of nodes/bar elements.

In the last few days I've been trying to implement 3 Noded Plate Elements in a model but with no success. Is there any place where I can find an example of how to use these elements?

Kind Regards

**Comment by epsi1on** [comment]
Currently the stress tensor in 3 node bending element is not a true value (it is a computational bug) but nodal displacement are almost accurate. please use `DktElement` class for 3 noded plate bending at this moment.

Thanks
